name: Auto Update

on:
  schedule:
  - cron: '*/30 * * * *'

jobs:
  deploy:
    name: Update packages
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bucket Updates
      uses: Ash258/Scoop-GithubActions@main-win
      env:
        GITH_EMAIL: development@voke.dev
        SKIP_UPDATED: '1'
